apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"        # etiqueta que busca el sidecar
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated.monitoring.svc.cluster.local:9090
        isDefault: true
        version: 1

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-distributed-query-frontend.monitoring.svc.cluster.local:3200
        version: 1
        editable: false