apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-camel
  labels:
    app: quarkus-camel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-camel
  template:
    metadata:
      labels:
        app: quarkus-camel
    spec:
      containers:
        - name: quarkus-camel
          image: carlos89/quarkus-camel:latest  # 🔁 Cambia esto por tu imagen
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
            - name: QUARKUS_OTEL_TRACES_EXPORTER
              value: otlp
            - name: QUARKUS_OTEL_METRICS_EXPORTER
              value: otlp  
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
              #value: "http://tempo-distributed-distributor.monitoring.svc.cluster.local:4317"
              #value: "http://alloy.alloy.svc.cluster.local:4317"
              value: http://otel-collector.otel-collector.svc.cluster.local:4317
            - name: QUARKUS_OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: QUARKUS_OTEL_SERVICE_NAME
              value: "quarkus-camel"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.namespace.name=${POD_NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-camel
spec:
  type: NodePort
  selector:
    app: quarkus-camel
  ports:
    - port: 80
      targetPort: 8081