apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-camel
  labels:
    app: quarkus-camel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-camel
  template:
    metadata:
      labels:
        app: quarkus-camel
    spec:
      containers:
        - name: quarkus-camel
          image: carlos89/quarkus-camel:latest  # 🔁 Cambia esto por tu imagen
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo-distributed-distributor.observability.svc.cluster.local:9095"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"  
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=quarkus-camel"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_SERVICE_NAME
              value: "quarkus-camel"  
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-camel
spec:
  type: NodePort
  selector:
    app: quarkus-camel
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30080  # 🔁 Puedes cambiar este puerto si lo deseas
