# monitoring/servicemonitor-myapp.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-quarkus-camel
  namespace: alloy
  labels:
    release: alloy
spec:
  selector:
    matchLabels:
      app: quarkus-camel            # etiqueta de tus pods
  namespaceSelector:
    matchNames:
      - default             # el namespace donde corre tu app
  endpoints:
    - port: http-metrics   # nombre del port en tu Deployment
      path: /metrics
      interval: 15s
