apiVersion: v1
kind: Service
metadata:
  name: tempo-backend
  namespace: observability
spec:
  selector:
    app.kubernetes.io/name: tempo
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP
