apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel-collector
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector   # ajusta según tu etiqueta
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      protocol: TCP
  type: ClusterIP
