# 1) Define el repositorio y la etiqueta de la imagen del Collector
image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.128.0"          # o la versión que prefieras
  pullPolicy: IfNotPresent

mode: daemonset
presets:
  kubernetesAttributes:
    enabled: true
  kubernetesEvents:
    enabled: true
  kubeletMetrics:
    enabled: true  

config:
  receivers:
    # Recibe métricas y trazas en formato OTLP (gRPC+HTTP)
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    kubeletstats:
      collection_interval: 10s
      auth_type: serviceAccount
      insecure_skip_verify: true
      endpoint: "https://minikube:10250"
      metric_groups:
        - node
        - pod
        - container      
          

  processors:
    # Convierte métricas de cumulativas a delta (recomendado para Dynatrace)
    cumulativetodelta: {}
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

  exporters:
    # Exportador HTTP OTLP hacia Dynatrace Metrics API
    otlphttp:
      endpoint: "https://sfv56284.live.dynatrace.com/api/v2/otlp"
      #path: "/api/v2/metrics/ingest"
      headers:
        Authorization: "Api-Token <token>"
      timeout: 10s
      retry_on_failure:
        enabled: true  
    debug:
      verbosity: detailed    

  service:
    pipelines:
      metrics:
        receivers:  [otlp,kubeletstats]
        processors: [cumulativetodelta, batch, memory_limiter]
        exporters:  [otlphttp,debug]
      traces:
       receivers: [otlp]
       processors: [batch]
       exporters: [otlphttp] 
